[project]
name = "scriptwriter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "googlesearch-python>=1.3.0",
    "ipykernel>=6.29.5",
    "openai>=1.97.0",
    "openai-agents>=0.2.2",
    "pydantic>=2.11.7",
]
